name: 'build fap'
author: 'Oleksii Kutuzov'
description: 'Github Action that builds your fap with ufbt'
branding:
  icon: 'align-left'  
  color: 'green'
inputs:
  fap-dir:
    description: 'Directory with your fap (you should checkout your repository to some folder'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout ufbt
      uses: actions/checkout@v3
      with:
        repository: flipperdevices/flipperzero-ufbt
        path: flipperzero-ufbt
        
    - name: Set path
      shell: bash
      run: echo "$GITHUB_WORKSPACE/flipperzero-ufbt" >> $GITHUB_PATH
      
    - name: Build fap
      shell: bash
      run: cd ${{ inputs.fap-dir }}; ufbt
